import React from "react";
import ImageCard from "@/components/ImageCard";
import UpButton from "@/components/UpButton";
import DownButton from "@/components/DownButton";
import Banner from "@/components/Banner";
import Card from "@/components/Card";
import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Description from "@/components/Description";

const HomePage = () => {
  return (
    <>
    <Head>
        <title>TaeRim Lee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className={styles.main}>
          <Banner
            textElements={[
              { text: "TaeRim Lee", level: "h1" },
              { text: "1995.10.12", level: "h3" },
              { text: "Blockchain & Backend Developer", level: "h2" },
            ]}
          />
      <div style={{ textAlign: "center" }}>
        <div style={{ display: "flex", justifyContent: "center", flexWrap: "wrap" }}>
          <Card textElements={[
            { text: "Contact", level: "h2" },
            { text: "　", level: "h4" },
            { text: "+82-10-3790-8221", level: "h4" },
            { text: "95decode@gmail.com", level: "h4" },
          ]} imageLinks={[
            { src: "/images/github.png", href: "https://github.com/95decode", alt: "Github" },
            { src: "/images/linkedin.png", href: "https://www.linkedin.com/in/95decode", alt: "Linkedin" }
          ]}/>
          <Card textElements={[
            { text: "Education", level: "h2" },
            { text: "　", level: "h4" },
            { text: "B.S. in Electronic Engineering", level: "h4" },
            { text: "M.S. in Electronic Engineering", level: "h4" },
            { text: "Sogang University, Seoul, Korea", level: "h4" },
          ]} imageLinks={[
            { src: "/images/sogang.png", href: "https://www.sogang.ac.kr/", alt: "Sogang Univ" },
          ]}/>
          <Card textElements={[
            { text: "Skills", level: "h2" },
            { text: "　", level: "h4" },
            { text: "Typescript", level: "h4" },
            { text: "Solidity", level: "h4" },
            { text: "Go", level: "h4" },
            { text: "Python", level: "h4" },
          ]} imageLinks={[
            { src: "/images/typescript.png", alt: "typescript" },
            { src: "/images/solidity.png", alt: "solidity" },
            { src: "/images/go.png", alt: "go" },
            { src: "/images/python.png", alt: "python" },
          ]}/>
        </div>
      </div>
      <div style={{ textAlign: "center" }}>
        <div style={{ display: "flex", justifyContent: "center", flexWrap: "wrap" }}>
          <ImageCard imageSrc="/images/sogang.png" alt="blockchain labs" text="Blockchain Labs" target="blockchain-labs-detail"/>
          <ImageCard imageSrc="/images/afreecatv.png" alt="afreecatv" text="AfreecaTV" target="afreecatv-detail"/>
          <ImageCard imageSrc="/images/hexlant.png" alt="hexlant" text="Hexlant"  target="hexlant-detail"/>
        </div>
      </div>
      <div id="blockchain-labs-detail" style={{ textAlign: "center", marginBottom: "2rem" }}>
        <Description textElements={[
          { text: "Sogang Univ. Blockchain labs", level: "h1" },
          { text: "foo", level: "h3" },
        ]} />
      </div>
      <div id="afreecatv-detail" style={{ textAlign: "center", marginBottom: "2rem" }}>
        <Description textElements={[
          { text: "AfreecaTv Freemeta", level: "h1" },
          { text: "bar", level: "h3" },
        ]} />
      </div>
      <div id="hexlant-detail" style={{ textAlign: "center", marginBottom: "2rem" }}>
        <Description textElements={[
          { text: "Hexlant", level: "h1" },
          { text: "baz", level: "h3" },
        ]} />
      </div>
      <UpButton /><DownButton />
    </main>
    </>
  );
};

export default HomePage;